# Generated by Django 5.2.6 on 2025-09-25 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('radio', 'Radio'), ('checkbox', 'Checkbox')], default='text', max_length=10)),
                ('options', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('address', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('profession', models.CharField(blank=True, max_length=80)),
                ('specialty', models.CharField(max_length=80)),
                ('contact_info', models.CharField(max_length=200)),
                ('degree', models.CharField(blank=True, max_length=80)),
                ('diploma', models.CharField(blank=True, max_length=80)),
                ('pg_degree', models.CharField(blank=True, max_length=80)),
                ('diplomate', models.CharField(blank=True, max_length=80)),
                ('superspeciality', models.CharField(blank=True, max_length=80)),
                ('mci_registration', models.CharField(blank=True, max_length=80)),
                ('pan', models.CharField(blank=True, max_length=20)),
                ('pan_copy', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('cancelled_cheque', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('visiting_card', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('optional_document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('clinic_name', models.CharField(blank=True, max_length=120)),
                ('qualification', models.CharField(blank=True, max_length=120)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('has_gst', models.BooleanField(default=False)),
                ('bank_account_name', models.CharField(blank=True, max_length=120, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=120, null=True)),
                ('account_no', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='wtestapp.doctor')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='wtestapp.question')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='surveys', to='wtestapp.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='wtestapp.survey'),
        ),
    ]
