# Generated by Django 5.2.6 on 2025-09-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtestapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='agreement_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
