# Generated by Django 5.2.6 on 2025-10-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtestapp', '0002_doctor_experience_doctor_medical_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_json',
            field=models.FileField(blank=True, help_text='Upload JSON file for survey questions', null=True, upload_to='surveys/'),
        ),
    ]
