# Generated by Django 5.2.6 on 2025-09-26 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtestapp', '0002_doctor_agreement_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='doctor',
        ),
        migrations.AddField(
            model_name='question',
            name='help_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Long Text'), ('radio', 'Multiple Choice (Single)'), ('checkbox', 'Multiple Choice (Multiple)'), ('yesno', 'Yes/No'), ('rating', 'Rating Scale'), ('number', 'Number Input'), ('email', 'Email'), ('phone', 'Phone Number')], default='text', max_length=15),
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_text', models.TextField()),
                ('digital_signature', models.TextField(blank=True, null=True)),
                ('signature_type', models.CharField(choices=[('drawn', 'Drawn'), ('typed', 'Typed')], default='drawn', max_length=20)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='agreements/')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signed_agreement', to='wtestapp.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='survey_responses/')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='wtestapp.doctor')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='wtestapp.survey')),
            ],
            options={
                'unique_together': {('doctor', 'survey')},
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='survey_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='wtestapp.surveyresponse'),
        ),
    ]
