# Generated by Django 5.2.6 on 2025-09-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtestapp', '0003_otpverification_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='prescription_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='prescription_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
