# Generated by Django 5.2.6 on 2025-10-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtestapp', '0003_survey_survey_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='gst_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
