# Generated by Django 5.2.6 on 2025-09-27 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtestapp', '0004_doctor_prescription_file_doctor_prescription_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='portal_type',
            field=models.CharField(blank=True, choices=[('CP', 'CP'), ('GC', 'GC')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='portal_type',
            field=models.CharField(blank=True, choices=[('CP', 'CP'), ('GC', 'GC')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='SurveyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wtestapp.doctor')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wtestapp.survey')),
            ],
            options={
                'unique_together': {('doctor', 'survey')},
            },
        ),
    ]
