# Generated by Django 5.2.6 on 2025-10-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtestapp', '0004_doctor_gst_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='agreement_text',
            field=models.TextField(blank=True, help_text='Optional - Leave blank to use default agreement template', null=True),
        ),
    ]
