# Generated by Django 5.2.6 on 2025-10-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtestapp', '0005_alter_agreement_agreement_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default amount for this survey', max_digits=10),
        ),
    ]
