# Generated by Django 5.2.6 on 2025-09-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtestapp', '0005_doctor_portal_type_survey_portal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='agreement_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
