# Generated by Django 5.2.6 on 2025-10-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtestapp', '0007_doctor_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='uploads/excel/')),
                ('survey_json', models.FileField(blank=True, null=True, upload_to='uploads/surveys/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
