# Generated by Django 5.2.6 on 2025-10-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtestapp', '0008_doctorexcelupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='designation',
            field=models.CharField(blank=True, help_text='Designation (ZSM/BDM/ZM/etc)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='emp1_mobile',
            field=models.CharField(blank=True, help_text='Manager 1 Mobile', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='emp1_name',
            field=models.CharField(blank=True, help_text='Manager 1 Name (ZSM/BDM/ZM)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='emp2_mobile',
            field=models.CharField(blank=True, help_text='Manager 2 Mobile', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='emp2_name',
            field=models.CharField(blank=True, help_text='Manager 2 Name', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='territory',
            field=models.CharField(blank=True, help_text='Territory/Location', max_length=200, null=True),
        ),
    ]
