# Generated by Django 5.2.6 on 2025-10-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtestapp', '0009_doctor_designation_doctor_emp1_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialty',
        ),
    ]
