# Generated by Django 5.2.6 on 2025-10-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtestapp', '0010_remove_doctor_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
