# Generated by Django 5.2.6 on 2025-10-17 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtestapp', '0011_doctor_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='wtestapp.doctor'),
        ),
    ]
