# Generated by Django 5.2.6 on 2025-10-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtestapp', '0012_change_agreement_to_foreignkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('gc', 'GC')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='portal_type',
            field=models.CharField(blank=True, choices=[('GC', 'GC')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='portal_type',
            field=models.CharField(blank=True, choices=[('GC', 'GC')], max_length=10, null=True),
        ),
    ]
