# Generated by Django 5.2.6 on 2025-10-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtestapp', '0013_alter_customuser_role_alter_doctor_portal_type_and_more'),
    ]

    operations = [
    ]
