# Generated by Django 5.2.6 on 2025-10-18 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtestapp', '0014_fix_survey_assignment'),
    ]

    operations = [
    ]
