# Generated by Django 5.2.6 on 2025-10-18 07:16

from django.db import migrations


def update_portal_choices(apps, schema_editor):
    Doctor = apps.get_model('wtestapp', 'Doctor')
    # Update existing records with null portal_type to 'GC'
    Doctor.objects.filter(portal_type__isnull=True).update(portal_type='GC')

class Migration(migrations.Migration):

    dependencies = [
        ('wtestapp', '0015_recreate_survey_assignment'),
    ]

    operations = [
        migrations.RunPython(update_portal_choices, reverse_code=migrations.RunPython.noop),
    ]
